"use strict";

FrameEditorBlockCatalog.register({
    type: 'text',
    name: 'Text Block',
    description: 'Place editable text anywhere in the layout.',
    icon: 'bi-type-h2',
    properties: [
        { setting: 'backgroundColorRaw', valueKey: 'backgroundColor', label: 'Background', type: 'color', allowTransparent: true },
        { setting: 'borderColor', label: 'Border color', type: 'color' },
        { setting: 'borderRadius', label: 'Border radius', type: 'number', min: 0, max: 48, step: 1, unit: 'px' },
        { setting: 'borderWidth', label: 'Border width', type: 'number', min: 0, max: 20, step: 1, unit: 'px' },
        { setting: 'color', label: 'Color', type: 'color' },
        { setting: 'dropCap', label: 'Drop Cap', type: 'checkbox' },
        { setting: 'fontSize', label: 'Font size', type: 'number', min: 8, max: 240, step: 1, unit: 'px' },
        { setting: 'fontStyle', label: 'Font style', type: 'select', options: [{ id: 'normal', label: 'Normal' }, { id: 'italic', label: 'Italic' }] },
        { setting: 'fontWeight', label: 'Font weight', type: 'number', min: 100, max: 900, step: 100 },
        { setting: 'letterSpacing', label: 'Letter spacing', type: 'number', min: -10, max: 40, step: 0.5, unit: 'px' },
        { setting: 'lineHeight', label: 'Line height', type: 'number', min: 1, max: 3, step: 0.1 },
        { setting: 'paddingBottom', label: 'Padding bottom', type: 'number', min: 0, max: 2000, step: 1, unit: 'px' },
        { setting: 'paddingLeft', label: 'Padding left', type: 'number', min: 0, max: 2000, step: 1, unit: 'px' },
        { setting: 'paddingLinked', label: 'Padding linked', type: 'checkbox' },
        { setting: 'paddingRight', label: 'Padding right', type: 'number', min: 0, max: 2000, step: 1, unit: 'px' },
        { setting: 'paddingTop', label: 'Padding top', type: 'number', min: 0, max: 2000, step: 1, unit: 'px' },
        { setting: 'text', label: 'Text', type: 'textarea' },
        { setting: 'textAlign', label: 'Text align', type: 'select', options: [{ id: 'left', label: 'Left' }, { id: 'center', label: 'Center' }, { id: 'right', label: 'Right' }] },
        { setting: 'textDecoration', label: 'Text decoration', type: 'select', options: [{ id: 'none', label: 'None' }, { id: 'underline', label: 'Underline' }, { id: 'line-through', label: 'Line-through' }] },
        { setting: 'textPositionX', label: 'Text position X', type: 'select', options: [{ id: 'left', label: 'Left' }, { id: 'center', label: 'Center' }, { id: 'right', label: 'Right' }, { id: 'custom', label: 'Custom' }] },
        { setting: 'textPositionY', label: 'Text position Y', type: 'select', options: [{ id: 'top', label: 'Top' }, { id: 'center', label: 'Center' }, { id: 'bottom', label: 'Bottom' }, { id: 'custom', label: 'Custom' }] },
        { setting: 'textTransform', label: 'Text transform', type: 'select', options: [{ id: 'none', label: 'None' }, { id: 'uppercase', label: 'Uppercase' }, { id: 'lowercase', label: 'Lowercase' }, { id: 'capitalize', label: 'Capitalize' }] },
        { setting: 'width', label: 'Width', type: 'number', min: 0, max: 20000, step: 4, unit: 'px' }
    ],
    createBlock(context) {
        const defaultColor = context.getDefaultColor ? context.getDefaultColor() : '#111111';
        return {
            id: context.id,
            type: 'text',
            text: context.translate ? context.translate('This is a text block') : 'This is a text block',
            xPct: context.xPct,
            yPct: context.yPct,
            width: 0,
            fontSize: 32,
            fontSizePreset: 'm',
            fontWeight: 400,
            fontStyle: 'normal',
            color: defaultColor,
            backgroundColor: 'transparent',
            paddingTop: 0,
            paddingRight: 0,
            paddingBottom: 0,
            paddingLeft: 0,
            paddingX: 0,
            paddingY: 0,
            paddingLinked: true,
            borderWidth: 0,
            borderRadius: 0,
            borderColor: defaultColor,
            rotation: 0,
            lineHeight: 1.5,
            letterSpacing: 0,
            textDecoration: 'none',
            textTransform: 'none',
            dropCap: false,
            textAlign: 'left',
            textPositionX: 'left',
            textPositionY: 'top',
            parentId: context.parentId,
            childOrder: context.childOrder,
            columnIndex: context.columnIndex
        };
    }
});